export const AdoptionData = [
    {
        id: 'cat123',
        type: 'cat',
        breed: 'europejska',
        url: "https://www.kundelek.rsoz.org/fabia/",
        name: "Fabia",
        age: 'junior',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/02/IMG_2548-scaled.jpg",
        desc1: "Fabia trafiła do schroniska w roku 2023, mając ok. 2 lata. Jest to przyjazna, odważna kotka.",
        desc2: "Jest odrobaczona, zaszczepiona, zaczipowana i wysterylizowana."
    },
    {
        id: 'cat124',
        type: 'cat',
        breed: 'egzotyk',
        url: "https://www.kundelek.rsoz.org/klaudia/",
        name: "Klaudia",
        age: 'junior',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/02/425799762_780279687474396_9035989213827660437_n.jpg",
        desc1: "Klaudia trafiła do schroniska w roku 2023, mając ok. 1,5 roku. Jest to przyjazna, energiczna kotka.",
        desc2: "Jest odrobaczona, zaszczepiona, zaczipowana i wysterylizowana."
    },
    {
        id: 'cat125',
        type: 'cat',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/narnia/",
        name: "Narnia",
        age: 'junior',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/02/425689932_780687620766936_5825848859490781704_n.jpg",
        desc1: "Narnia trafiła do schroniska w roku 2024, mając ok. 2 lata. Jest to spokojna, przyjazna kotka.",
        desc2: "Jest odrobaczona, zaszczepiona i zaczipowana."
    },
    {
        id: 'cat126',
        type: 'cat',
        breed: 'europejska',
        url: "https://www.kundelek.rsoz.org/nadia/",
        name: "Nadia",
        age: 'junior',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/02/425684288_780686170767081_898942863581270685_n.jpg",
        desc1: "Nadia trafiła do schroniska w roku 2024, mając ok. 3 lata. Jest to spokojna, przyjazna kotka.",
        desc2: "Jest odrobaczona, zaszczepiona i zaczipowana."
    },
    {
        id: 'cat127',
        type: 'cat',
        breed: 'europejska',
        url: "https://www.kundelek.rsoz.org/frida/",
        name: "Frida",
        age: 'junior',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/01/IMG_2729-scaled.jpg",
        desc1: "Frida trafiła do schroniska w roku 2023, mając ok. 1,5 roku. Jest to spokojna, przyjazna kotka.",
        desc2: "Jest odrobaczona, zaszczepiona, zaczipowana i wysterylizowana."
    },
    {
        id: 'cat128',
        type: 'cat',
        breed: 'europejska',
        url: "https://www.kundelek.rsoz.org/tajger/",
        name: "Tajger",
        age: 'junior',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/01/IMG_2330-scaled.jpg",
        desc1: "Tajger to ok. 7 miesięczny, spokojny, ostrożny w stosunku do człowieka kocurek, który z czasem nabiera odwagi.",
        desc2: "Jest odrobaczony, zaszczepiony, zaczipowany i wykastrowany."
    },
    {
        id: 'cat129',
        type: 'cat',
        breed: 'europejska',
        url: "https://www.kundelek.rsoz.org/frania/",
        name: "Frania",
        age: 'junior',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/12/414013193_756205083215190_5573773597674737639_n.jpg",
        desc1: "Frania trafiła do schroniska w roku 2023, mając ok. 3 lata. Jest to spokojna, przyjazna kotka.",
        desc2: "Jest odrobaczona, zaszczepiona, zaczipowana i wysterylizowana."
    },
    {
        id: 'cat130',
        type: 'cat',
        breed: 'europejska',
        url: "https://www.kundelek.rsoz.org/tombak/",
        name: "Tombak",
        age: 'old',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/12/408815171_744768157692216_4942452859810361209_n.jpg",
        desc1: "Tombak trafił do schroniska w roku 2023, mając ok. 10 lat. Jest to dorosły, przyjazny kocur, który ostatnimi czasy żył jako kot wolno żyjący, ale świetnie się odnajdzie w ciepłym, bezpiecznym domu\nJest odrobaczony, zaszczepiony, zaczipowany i wykastrowany.\nKontakt w sprawie adopcji: 510170787"
    },
    {
        id: 'cat131',
        type: 'cat',
        breed: 'europejska',
        url: "https://www.kundelek.rsoz.org/jozef/",
        name: "Józef",
        age: 'old',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/12/408793351_744765387692493_3128269798132011324_n.jpg",
        desc1: "Józef kot który trafił do schroniska w roku 2023, mając ok. 4 lata. Diagnoza: brak czucia głębokiego w kończynach tylnych i ogonie.",
        desc2: "Mimo tego, w tych zmęczonych oczach można było dostrzec iskrę niezłomnej woli życia. Każdy kolejny oddech, choć trudny, był aktem nieugiętej determinacji. Józef nie poddał się łatwo. Nawet w obliczu ekstremalnego cierpienia, widać w nim było pragnienie życia, które trwa dalej. Józef przeszedł operację, stracił ogon i niedowidzi. Aby odzyskać sprawność w łapach dzielnie znosił rehabilitację. mimo swoich „braków” i traumatycznych przeżyć Józef świetnie sobie radzi w codziennym funkcjonowaniu."
    },
    {
        id: 'cat132',
        type: 'cat',
        breed: 'europejska',
        url: "https://www.kundelek.rsoz.org/kola-2/",
        name: "Kola",
        age: 'old',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/12/407920117_743642821138083_7389264923116692763_n.jpg",
        desc1: "Kola to ok. 10 letnia, spokojna kotka.\nJest odrobaczona, zaszczepiona i zaczipowana.\nKontakt w sprawie adopcji: 510170787"
    },
    {
        id: 'cat133',
        type: 'cat',
        breed: 'europejska',
        url: "https://www.kundelek.rsoz.org/kalina/",
        name: "Kalina",
        age: 'old',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/08/Kalina3.jpg",
        desc1: "Kalina trafiła do schroniska w roku 2017, mając ok. 3 lata. Jest to kotka dość lękliwie reagująca na człowieka, jednakże daje się głaskać. Nowy opiekun będzie musiał wykazać cierpliwość w zdobywaniu jej uczucia.\nKalina jest odrobaczona, zaszczepiona, wysterylizowana i zaczipowana.\nKontakt w sprawie adopcji: 510 170 787"
    },
    {
        id: 'cat134',
        type: 'cat',
        breed: 'europejska',
        url: "https://www.kundelek.rsoz.org/przyklad-wpisu-koty-dorosle/",
        name: "Zidan",
        age: 'junior',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/08/Zidan3.jpg",
        desc1: "Zidan trafił do schroniska w roku 2021, mając ok. 1 rok. Jest to przyjazny, chętny do zabawy, chociaż unikający bezpośredniego kontaktu z człowiekiem.\nJest odrobaczony, zaszczepiony, zaczipowany i wykastrowany.\nKontakt w sprawie adopcji: 510 170 787"
    },
    {
        id: 'dog110',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/wini/",
        name: "Wini",
        age: 'junior',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/02/IMG_3023-scaled.jpg",
        desc1: "Wini trafiła do schroniska w roku 2024, mając ok. 1 rok. Jest to nieduża, nieśmiała, przyjazna, bardzo przekupna sunia.",
        desc2: "Jest odrobaczona, zaszczepiona i zaczipowana."
    },
    {
        type: 'dog',
        id: 'dog111',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/wenus/",
        name: "Wenus",
        age: 'junior',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/02/424955176_779336694235362_9006311674320455006_n.jpg",
        desc1: "Wenus trafiła do schroniska w roku 2024, mając ok. 1 rok. Jest to mała, przyjazna sunia.",
        desc2: "Jest odrobaczona, zaszczepiona i zaczipowana."
    },
    {
        type: 'dog',
        id: 'dog112',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/milan/",
        name: "Milan",
        age: 'old',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/01/421861592_777630467739318_2595749873612761891_n.jpg",
        desc1: "Milan trafił do schroniska w roku 2023, mając ok. 8 lat. Jest to mały, kudłaty, przyjazny piesek.",
        desc2: "Jest odrobaczony, zaszczepiony, zaczipowany i wykastrowany."
    },
    {
        type: 'dog',
        id: 'dog113',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/miki/",
        name: "Miki",
        age: 'old',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/01/421888810_777574297744935_2992652309042137063_n.jpg",
        desc1: "Miki trafił do schroniska w roku 2023, mając ok. 5 lat. Jest to nieduży, przyjazny piesek.",
        desc2: "Jest odrobaczony, zaszczepiony, zaczipowany i wykastrowany."
    },
    {
        type: 'dog',
        id: 'dog114',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/wedel/",
        name: "Wedel",
        age: 'old',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/01/IMG_2914-scaled.jpg",
        desc1: "Wedel trafił do schroniska w roku 2024, mając ok. 5 lat. Jest to nieduży, przyjazny pies.",
        desc2: "Jest odrobaczony, zaszczepiony i zaczipowany."
    },
    {
        type: 'dog',
        id: 'dog115',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/wento/",
        name: "Wento",
        age: 'junior',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/01/IMG_2866-scaled.jpg",
        desc1: "Wento trafił do schroniska w roku 2024, mając ok. 2 lata. Jest to przyjazny, większy pies w typie flat coated retriever.",
        desc2: "Jest odrobaczony, zaszczepiony i zaczipowany."
    },
    {
        id: 'dog116',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/saba/",
        name: "Saba",
        age: 'old',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/01/420088580_770270458475319_7652273727402736006_n.jpg",
        desc1: "Saba trafiła do schroniska w roku 2024, mając ok. 6 lat. Jest to średniej wielkości, energiczna, przyjazna suczka.",
        desc2: "Jest odrobaczona, zaszczepiona i zaczipowana."
    },
    {
        id: 'dog117',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/moli/",
        name: "Moli",
        age: 'old',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/01/419221368_768872805281751_8419540351058326677_n.jpg",
        desc1: "Moli trafiła do schroniska w roku 2023, mając ok. 5 lat. Jest to mała, przyjazna, energiczna suczka.",
        desc2: "Jest odrobaczona, zaszczepiona, zaczipowana i wysterylizowana."
    },
    {
        id: 'dog118',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/miecio/",
        name: "Miecio",
        age: 'junior',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/01/419254114_767795398722825_5747784587202574580_n.jpg",
        desc1: "Miecio trafił do schroniska w roku 2023, mając ok. 1 rok. Jest to średniej wielkości, spokojny, przyjazny pies. W pierwszym kontakcie z człowiekiem może nie być wylewny.",
        desc2: "Jest odrobaczony, zaszczepiony i zaczipowany."
    },
    {
        id: 'dog119',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/mania/",
        name: "Mania",
        age: 'old',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2024/01/420053503_767661132069585_2132858206941888960_n.jpg",
        desc1: "Mania trafiła do schroniska w roku 2023, mając ok. 10 lat. Jest to spokojna, przyjazna suczka.",
        desc2: "Jest odrobaczona, zaszczepiona, zaczipowana i wysterylizowana."
    },
    {
        id: 'dog120',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/myszka/",
        name: "Myszka",
        age: 'junior',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/12/414083557_756994229802942_5176903907986536539_n.jpg",
        desc1: "Myszka trafiła do schroniska w roku 2023, mając ok. 3 lata. Jest to przyjazna, nieduża suczka.",
        desc2: "Jest odrobaczona, zaszczepiona, zaczipowana i wysterylizowana."
    },
    {
        id: 'dog121',
        type: 'dog',
        breed: 'w typie wyżła',
        url: "https://www.kundelek.rsoz.org/batler/",
        name: "Batler",
        age: 'old',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/12/315100819_5851092491609208_5836123428949613148_n.jpg",
        desc1: "Batler trafił do schroniska w roku 2022, mając ok. 9 lat. Jest to większy pies w typie wyżła niemieckiego szorstkowłosego.",
        desc2: "Jest odrobaczony, zaszczepiony, zaczipowany i wykastrowany."
    },
    {
        id: 'dog122',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/benio/",
        name: "Benio",
        age: 'junior',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/12/410973185_750001010502264_7693291953678812287_n.jpg",
        desc1: "Benio trafił do schroniska w roku 2023, mając ok. 1 rok. Jest to średniej wielkości, przyjazny, energiczny psiak.",
        desc2: "Swoim poprzednim właścicielom został odebrany, ponieważ pozostawili go na długi okres czasu przywiązanego do budy, bez dostępu do karmy i wody. Wychudzonego psa zauważyła przypadkowa osoba. Możliwe, że w wyniku zagłodzenia konieczne było usunięcie śledziony. Obecnie Benio jest zdrowy i czeka na nowy dom."
    },
    {
        id: 'dog123',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/dina/",
        name: "Dina",
        age: 'old',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/12/410835904_748975787271453_2726853478612714874_n.jpg",
        desc1: "Dina trafiła do schroniska w roku 2023, mając ok. 6 lat. Jest to nieduża, przyjazna, spokojna suczka.",
        desc2: "Jest odrobaczona, zaszczepiona, zaczipowana i wysterylizowana."
    },
    {
        id: 'dog124',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/majka/",
        name: "Majka",
        age: 'old',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/12/410159798_748667667302265_8292027791671187075_n.jpg",
        desc1: "Majka trafiła do schroniska w roku 2023, mając ok. 8 lat. Jest to średniej wielkości, przyjazna, chociaż ostrożna w pierwszym kontakcie suczka.",
        desc2: "Jest odrobaczona, zaszczepiona, zaczipowana i wysterylizowana."
    },
    {
        id: 'dog125',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/bizi/",
        name: "Bizi",
        age: 'old',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/12/409930985_747297867439245_6443774299511151147_n.jpg",
        desc1: "Bizi trafiła do schroniska w roku 2o23, mając ok. 6 lat. Jest to mała, ostrożna w stosunku do człowieka suczka.",
        desc2: "Jest odrobaczona, zaszczepiona, zaczipowana i wysterylizowana."
    },
    {
        id: 'dog126',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/bogusia/",
        name: "Bogusia",
        age: 'old',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/12/410916504_747293260773039_525417813781440579_n.jpg",
        desc1: "Bogusia trafiła do schroniska w roku 2023, mając ok. 4 lata. Jest to średniej wielkości, dość wycofany w stosunku do człowieka pies.",
        desc2: "Do niedawna mieszkała przy chacie pod lasem, pod opieką starszej osoby, w stadzie innych psów."
    },
    {
        id: 'dog127',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/mati/",
        name: "Mati",
        age: 'junior',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/12/410964144_747284604107238_5193318287707739271_n.jpg",
        desc1: "Mati trafił do schroniska w roku 2023, mając ok. 2 lata. Jest to średniej wielkości, przyjazny pies.",
        desc2: "Jest odrobaczony, zaszczepiony, zaczipowany i wykastrowany."
    },
    {
        id: 'dog128',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/lucek/",
        name: "Lucynka",
        age: 'old',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/12/407789708_741229188046113_419184812535012009_n.jpg",
        desc1: "Lucynka trafiła do schroniska w roku 2023, mając ok. 8 lat. Jest to średniej wielkości, kudłata, przyjazna suczka. .",
        desc2: "Jest odrobaczona, zaszczepiona i zaczipowana."
    },
    {
        id: 'dog129',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/dragon/",
        name: "Dragon",
        age: 'junior',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/11/371923048_686068796895486_5252364435550243690_n.jpg",
        desc1: "Dragon trafił do schroniska w roku 2023, mając ok. 1,5 roku. Jest to średniej wielkości, przyjazny, energiczny pies.",
        desc2: "Jest odrobaczony, zaszczepiony, zaczipowany i wykastrowany."
    },
    {
        id: 'dog130',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/tales/",
        name: "Tales",
        age: 'junior',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/08/Tales1.jpg",
        desc1: "Tales trafił do schroniska w roku 2023, mając ok. 2 lata. Jest to duży, przyjazny, energiczny pies. Zna podstawowe komendy.\nJest odrobaczony, zaszczepiony, zaczipowany i wykastrowany.\nKontakt w sprawie adopcji: 510 170 787"
    },
    {
        id: 'dog131',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/zuzia/",
        name: "Abi",
        age: 'junior',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/08/Abi-1-1.jpg",
        desc1: "Abi trafiła do schroniska w roku 2023, mając ok. 1 rok. Jest to średniej wielkości, przyjazna suczka.\nJest odrobaczona, zaszczepiona i zaczipowana.\nKontakt w sprawie adopcji: 510 170 787"
    },
    {
        id: 'dog132',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/sato/",
        name: "Sato",
        age: 'old',
        gender: 'male',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/08/Sato1.jpg",
        desc1: "Sato trafił do schroniska w styczniu 2020 r., mając ok. 5 miesięcy. Jest to średniej wielkości, spokojny piesek, który potrzebuje czasu i cierpliwości, żeby zaczął merdać ogonem i rozdawał całusy.\nJest odrobaczony, zaszczepiony, zaczipowany i wykastrowany.\nKontakt w sprawie adopcji: 510 170 787"
    },
    {
        id: 'dog133',
        type: 'dog',
        breed: 'mieszana',
        url: "https://www.kundelek.rsoz.org/daria/",
        name: "Daria",
        age: 'old',
        gender: 'female',
        img: "https://www.kundelek.rsoz.org/wp-content/uploads/2023/08/Daria2.jpg",
        desc1: "Daria trafiła do schroniska w roku 2023, mając ok. 6 lat. Jest to spokojna, większa suczka.\nJest odrobaczona, zaszczepiona i zaczipowana.\nKontakt w sprawie adopcji: 510 170 787"
    }
];